### ISSUE TITLE
gui nicety: trying to track before setting tracking parameters errors

### ISSUE THREAD

**Issue by arobie** [kristinbranson/APT#227]
currently trying to track (shortcut key or button) before setting parameters or training errors:
Error using CPRLabelTracker/track (line 1417)
Please specify tracking parameters.

Error in Labeler/track (line 7939)
      tObj.track(tblMFT,varargin{:});

Error in LabelerGUI>pbTrack_Callback (line 1796)
handles.labelerObj.track(tm,'wbObj',wbObj);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in LabelerGUI (line 33)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)LabelerGUI('pbTrack_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.

Would be nice if it opened a dialog that told you to set parameters and train. or open parameters gui for you ;)

(similarly trying to track before setting parameters also throws error which is good in theory, not training with default params, but could be more user friendly). 

PS - only bumped this because I used the JAABA shortcut for removing body trajectory from plotting. heehee).

**Comment by kristinbranson** [comment]
Because of the way the code is abstracted, the easiest thing to do was put in a check and give you an error dialog saying parameters had not been set, or whatever the error message is, and not opening the tracking parameters. I implemented this. Is this good enough? It is possible to implement the opening tracking parameters as suggested. Let me know if you think this is important.

**Comment by arobie** [comment]
that's works great! much better than erroring out :)
