### ISSUE TITLE
show predictions for current target doesn't work on imported predictions in multianimal mode

### ISSUE THREAD

**Issue by roian** [kristinbranson/APT#388]
interestingly...shows the current target...but not the predictions...?  when using "show imported predictions for current target only"

**Comment by allenleetc** [comment]
To confirm, by 'current target' you mean that you selected an imported-predicted mouse? As opposed to a regular-predicted mouse, or a labeled target.

If other targets were hidden, and you wanted to change (imported) targets, how would you expect to do that? It would seem to be obnoxious to have to i) unhide, ii) select-new-imported-tgt, iii) re-hide.

How do people think about selection of linked predictions/tracklets? @mkabra @kristinbranson Eg couple examples
1. Repurposing of Targets table. Since there is currently no identification of Labeled targets with stitched targets (?), this table would need two 'modes' or 'tabs': one for Labels, one for Preds.
2. A new "global tracklet view" that shows all tracklets linked/found, with ability to select. Eg could be in the timeline with a single colored trace per target, or could be separate pop-up pane etc.

**Comment by mkabra** [comment]
Both the utilities should be pretty helpful. For 2 though, we could try to
repurpose Switch Target UI. And maybe we could add a few ways of selection
trajectories e.g., min/max length, current/all movies, min/max number of
breaks, min/max number of missing frames etc? I think we should do Switch
Target first, and if we still feel a need then maybe do the tabs?

Mayank

**Comment by allenleetc** [comment]
Ah yes I had forgotten about the Switch Targets table. Yes good idea we could repurpose that UI. Looks like that pane needs to be updated for MA in any case.

Switch Targets never comes to mind for me, wonder if it could use a shortcut or some kind of associated UI control (eg small button/widget in Targets Table)? Maybe that subsumes the Tabs idea.

**Comment by allenleetc** [comment]
this should be fixed now. note if "show preds/imported for current target" is turned on, all other targets will be hidden entirely; switching targets (in an MA project) must be done with the Switch Targets table.
